app_deployment:
  appName: access-denied-page
  image: nexus-docker-craigmiller160.ddns.net/access-denied-page:latest
  ports:
    - containerPort: 443
  commonProbe:
    httpGet:
      path: /healthcheck
      port: 443
      scheme: HTTPS
  secure_ingress:
    name: access-denied-page-ingress
    backendIsHttps: true
    hosts:
      - name: apps.craigmiller160.us
        services:
          - path: /access-denied(/.*)?
            serviceName: access-denied-page
            portNumber: 443